### ISSUE TITLE
When will a new version be released？ The types of 5.0.1 is not match

### ISSUE THREAD

**Issue by mankeheaven** [fastify/fastify-leveldb#118]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

import { FastifyPlugin } from "fastify";
FastifyPlugin  is deprecated

**Comment by Eomm** [comment]
Done https://github.com/fastify/fastify-leveldb/releases/tag/v5.1.0

Thanks for reporting
