### ISSUE TITLE
is fastify-leveldb es6 / import compatible ?

### ISSUE THREAD

**Issue by scenaristeur** [fastify/fastify-leveldb#124]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi , i only see a common/require example in README and test. 
Is this plugin ES6 / import compatible ? 
Do you have an example ?
Thxs

**Comment by gurgunday** [comment]
Yes it is, just replace require with import
