### ISSUE TITLE
Add support for memdown and other abstract-leveldown stores

### ISSUE THREAD

**Issue by millette** [fastify/fastify-leveldb#30]
The plugin currently depends on `level` which automatically imports `leveldown` and returns a nicely configured `levelup` instance.

For some use cases, even testing, it would be convenient to replace `leveldown` with `memdown`.

Aside from `name` and `options` keys, a 3rd key would identify the abstract-leveldown compliant store (maybe `store`). If provided, use that instead of the default `leveldown`.

**Comment by mcollina** [comment]
Would you like to send a PR?

Il giorno 1lun 17 giu 2019 alle 05:48 Robin Millette <
notifications@github.com> ha scritto:

**Comment by millette** [comment]
A couple more things (for a major release):

* Submit the change upstream to level although that might defeat its purpose (simplicity)
* Remove `leveldb` dependency and make it optional (or a peer, not sure which would be more appropriate) since it might not be used at all (using `memdown` instead).

**Comment by millette** [comment]
I'll close this, might open abinother issue about making leveldown optionnal.
