### ISSUE TITLE
major: make leveldown an optionnal dep

### ISSUE THREAD

**Issue by millette** [fastify/fastify-leveldb#32]
Now that #30 has landed, might we remove the hard dependency on `leveldown` as part of a major release?

Thoughts?

**Comment by mcollina** [comment]
I would like to keep it working out of the box. This module is called fastify-leveldb after all.
Maybe we can split this module into two.

**Comment by millette** [comment]
Maybe a new `fastify-level` (or `fastify-leveldb-lite` module with a peerDep on `leveldown`, and have `fastify-leveldb` depend on it, basically only adding the `leveldown` dep?

**Comment by mcollina** [comment]
peerDependencies are awkward at best, and they are thinking of making npm installing peerDeps by default in the next major.

I'm +1 on dropping the leveldown dep.

**Comment by millette** [comment]
So, move leveldown to peerDeps and add it to devDeps (for the tests)? Plus a note in the readme?

Did I understand?

**Comment by mcollina** [comment]
I would not include it in peerDeps at all.
